### ISSUE TITLE
Missing settings 

### ISSUE THREAD

**Issue by MVukanichh** [fwtechn/WCNSS_qcom_cfg#1]
Hello. I've stumbled upon this repository yesterday and I wanted to see the differences betweens yours and default file. I've noticed that there are some settings missing from your file that are found in default one on my phone. 
Example being: gEnableImps

Why is that? Thanks.

**Comment by MVukanichh** [comment]
Oh it's not that I need them, quite frankly I don't know what each parameter does anyway. Does that mean that parameters I can find in my WCNSS file exist and are used on my phone or how can I check that?

**Comment by FWTechn** [comment]
I don't know in detail too. I know part of it only. We have to connect to wifi yor turn on tethering and find the slight difference. However, I feel that there are many parameters that have no effect.
